routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::group(['middleware'=>['auth']],function(){

Route::get('/', function () {
    return redirect('home');
});



Route::get('/home', 'HomeController@index')->name('home');

Route::resource('restaurant', 'RestaurantController');

//Route::get('product/create/{id}', 'ProductController@create');
//Route::resource('product', 'ProductController');


Route::get('product/build/{id}', ['as' => 'product.create', 'uses' => 'ProductController@create']);
Route::get('product/lista/{id}', 'ProductController@lista')->name('product.lista');
Route::get('product/getProduct/{id}', 'ProductController@getProduct')->name('product.get');
Route::get('product/addCart/{id}', 'ProductController@addToCart');

Route::get('user/edit','UserController@create');
Route::post('updateUser','UserController@store');


Route::get('cart','CartController@index');
Route::get('cartValue','CartController@getValues');
Route::post('cartUpdateItem/{id}','CartController@updateCart');
Route::delete('removeCartItem/{id}','CartController@removeItemCart');

Route::get('pedidos','PedidoController@index');

Route::post('sendEmail','MailController@send');

Route::resource('product', 'ProductController', ['names' => [
    'create' => 'product.build'
]]);

});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = ['nome','valor','desc','restaurants_id'];
    protected $table = 'products';
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;



use Illuminate\Http\Request;
use Session;
use Redirect;

use App\Product;
use App\Restaurant;

use App\Http\Controllers\UploadFile;



class ProductController extends Controller
{
    public function addToCart($id){


        $product = Product::find($id);

        if(!$product) {

            abort(404);

        }

        $cart = session()->get('cart');


        if(!$cart) {

            $cart = [
                $id => [
                    "name" => $product->nome,
                    "qtd" => 1,
                    "desc" => $product->desc,
                    "valor" => $product->valor,
                    "image" => $product->image
                ]
            ];

            session()->put('cart', $cart);
            Session::flash('message','Product adicionado ao carrinho com sucesso!');
            return redirect()->back();
        }


        if(isset($cart[$id])) {

            $cart[$id]['qtd']++;

            session()->put('cart', $cart);
            Session::flash('message','Product adicionado ao carrinho com sucesso!');
            return redirect()->back();

        }

        // if item not exist in cart then add to cart with quantity = 1
        $cart[$id] = [
            "name" => $product->nome,
            "qtd" => 1,
            "desc" => $product->desc,
            "valor" => $product->valor,
            "image" => $product->image
        ];

        session()->put('cart', $cart);

        return redirect()->back()->with('success', 'Product added to cart successfully!');
    }

    public function updateCart(Request $request)
    {
        if($request->id and $request->quantity)
        {
            $cart = session()->get('cart');

            $cart[$request->id]["qtd"] = $request->quantity;

            session()->put('cart', $cart);

            session()->flash('success', 'Cart updated successfully');
        }
    }

    public function removeItemCart(Request $request)
    {
        if($request->id) {

            $cart = session()->get('cart');

            if(isset($cart[$request->id])) {

                unset($cart[$request->id]);

                session()->put('cart', $cart);
            }

            session()->flash('success', 'Product removed successfully');
        }
    }




    public function getProduct($id){

        return Product::find($id);

    }

    public function lista($id)
    {
        $products = Product::where('restaurants_id',$id)->orderBy('id','desc')->paginate(3);

        return view('product.lista', compact('products'));
    }

    public function index()
    {
        self::create();

        return view('product.index', compact('products','product'));
    }

    public function create($id)    {


        $products = Product::where('restaurants_id',$id)->get();
        $product = new Product();
        return view('product.index', compact('product', 'products','id'));
    }

    public function store(Request $request)
    {

        if($request->id){
            $product = Product::find($request->id);
        }else{
            $product = new Product();
        }

        $product->fill($request->all());


        if ($request->file('image')) {

            if ($product->image) {
                UploadFile::deletedFile($product->image);
            }

            $product->image = UploadFile::upload($request->file('image'), 'IMG');
        }

        $product->save();
        return $request->restaurants_id;
    }


    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $product = Product::find($id);
        $products = Product::all();

        if($product == null){


        }




        return view('product.index', compact('product', 'products'));
    }


    public function update(Request $request, $id)
    {

        $product = Product::find($id);

        $product->fill($request->all());

        if ($request->file('image')) {

            if ($product->image) {
                UploadFile::deletedFile($product->image);
            }

            $product->image = UploadFile::upload($request->file('image'), 'IMG');
        }

        $product->save();


        Session::flash('message', 'Atualizado com sucesso');
        return Redirect::to('product');
    }


    public function destroy($id)
    {
        Product::find($id)->delete();
        return ['true'];
    }
}

resources/views/product/cart.blade.php
@extends('layouts.app')



@section('content')
    <div class="container mb-4">
        <div class="row">
            <div class="col-12">
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th scope="col"></th>
                            <th scope="col">Produto</th>
                            <th scope="col" class="text-center">Quantidade</th>
                            <th scope="col" class="text-right">Preço</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>

                        @if(session('cart'))

                            @foreach(session('cart') as $x => $id )
                                <tr>
                                    <td><img src="{{asset('storage/'.$id['image'])}}" width="50px"/></td>
                                    <td> {{ $id['name'] }}</td>

                                    <td><input class="form-control test" type="text" id="qtdItem" data-id="{{ $x }}" value=" {{ $id['qtd'] }} "/></td>

                                    <td class="text-right">R$ {{ $id['valor'] }} * {{ $id['qtd'] }} </td>
                                    <td class="text-right">
                                        <button class="retirar" data-id="{{ $x }}" class="btn btn-sm btn-danger">X</button>
                                    </td>

                                </tr>
                            @endforeach



                        @endif


                        <tr>

                            <td></td>
                            <td></td>
                            <td></td>
                            <td><strong>Total</strong></td>
                            <td class="text-right" id="totalValue">R$<strong ></strong></td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="col mb-2">
                <div class="row">
                    <div class="col-sm-12  col-md-6">

                    </div>
                    <div class="col-sm-12 col-md-6 text-right">
                        <button class="btn btn-lg btn-block btn-success text-uppercase" id="finalizarPedido">Finalizar</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/product/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">

                    <div class="card mb-3">
                        <div class="row no-gutters">

                            <div class="col-md-12">


                               {{ Form::open(array('id'=>'formProduct','files' => 'true')) }}


                                @csrf
                                <div class="card-body row">
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            @if( $product->image )
                                                <img src="{{ asset('storage/'. $product->image) }}" id="image"
                                                     class="img-thumbnail rounded float-left" alt="...">
                                            @else
                                                <img src="{{ asset('img/product-bg.jpg') }}" id="image"
                                                     class="img-thumbnail rounded float-left" alt="...">
                                            @endif

                                            <input type="hidden" name="restaurants_id" value="{{$id}}">
                                                <input type="hidden" name="id" id="id" value="{{$product->id}}">

                                            <div class="custom-file">
                                                <input type="file" class="custom-file-input" name="image"
                                                       id="customFileLang">
                                                <label class="custom-file-label" for="customFileLang"
                                                       data-browse="Procurar">Selecione sua foto</label>
                                            </div>

                                        </div>
                                    </div>
                                    <div class="col-md-8">


                                        <div class="form-group">
                                            <label for="nome">Nome</label>
                                            <input type="text" value="{{ $product->name }}" class="form-control"
                                                   name="nome" required id="nome"
                                                   aria-describedby="resturanteName" placeholder="Nome do seu producte">

                                        </div>

                                        <div class="input-group mb-2">

                                            <div class="input-group-prepend">
                                                <div class="input-group-text">R$</div>
                                            </div>
                                            <input type="text" class="form-control" value="" required name="valor"
                                                   id="valor" placeholder="Digite aqui o valor!">
                                        </div>


                                        <div class="form-group">
                                            <label for="desc">Descrição</label>
                                            <textarea class="form-control" name="desc"
                                                      id="desc">{{ $product->desc }}</textarea>
                                            <small id="resturanteName" class="form-text text-muted">Chegou a hora de
                                                falar um
                                                pouquinho sobre seu produto.
                                            </small>
                                        </div>


                                            <button type="submit" id="btnform" class="btn btn-primary">Cadastrar</button>



                                    </div>

                                </div>
                                </form>
                            </div>
                        </div>
                    </div>


                <div id="lista">


                </div>


            </div>
        </div>
    </div>

@endsection

@section('js')

    <script>


        $( "#lista" ).load("{{ route('product.lista',['id'=>$id]) }}")


        $('#formProduct').on('submit', function(event){

            event.preventDefault();
            $.ajax({
                url:"{{ route('product.store') }}",
                method:"POST",
                data:new FormData(this),
                dataType:'JSON',
                contentType: false,
                cache: false,
                processData: false,
                success:function(data)
                {

                    Swal.fire(
                        'Parabéns!',
                        'Produto cadastrado com sucesso!',
                        'success'
                    );

                   $( "#lista" ).load("{{ route('product.lista',['id'=>$id]) }}");

                }
            })
        });





    </script>

@endsection

resources/views/product/lista.blade.php
<div class="my-3 p-3 bg-white rounded shadow-sm">
    <div class="col-12 row">

        <h6 class="border-bottom border-gray pb-2 mb-0"> Meus Produtos </h6>

    </div>


    @foreach($products as $product)
        <div class="media text-muted pt-3">

            @if($product->image)
                <img src="{{ asset('storage/'.$product->image)  }}" class="img-fluid" width="50px">
            @else
                <img src="{{ asset('img/product-bg.jpg') }}"
                     class="img-thumbnail rounded float-left" alt="..." width="50px">
            @endif
            <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                <div class="d-flex justify-content-between align-items-center w-100">
                    <strong class="text-gray-dark">{{ $product->nome  }}</strong>
                    <a href="#">R$: {{ $product->valor  }}</a>
                    <a href="#">Descrição :{{ $product->desc  }}</a>
                    <button class="updateRecord btn btn-info" data-id="{{ $product->id }}">Editar</button>
                    <button class="deleteRecord btn btn-danger" data-id="{{ $product->id }}">Excluir</button>


                </div>

            </div>
        </div>



    @endforeach


</div>

{{ $products->links() }}

<script>
    $(".deleteRecord").click(function () {
        var id = $(this).data("id");

        var token = $("meta[name='csrf-token']").attr("content");

        Swal.fire({
            title: 'Certeza que deseja excluir ?',
            text: "Essa ação não poderá ser revertida!",
            type: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Sim, excluir!'
        }).then((result) => {
            if (result.value) {
                $.ajax(
                    {
                        url: "/product/" + id,
                        method: 'delete',
                        data: {
                            "id": id,
                            "_token": token,
                        },
                        success: function (data) {

                            Swal.fire(
                                'Parabéns!',
                                'Produto excluído com sucesso!',
                                'success'
                            );


                        },
                        error: function (error) {
                            console.log(error)
                        }
                    });


            }


        });

    });


    $(".updateRecord").click(function () {

        var id = $(this).data("id");
        var token = $("meta[name='csrf-token']").attr("content");

        $.ajax(
            {
                url: "/product/getProduct/" + id,
                method: 'get',
                data: {
                    "id": id,
                    "_token": token,
                },
                success: function (data) {

                    $('#nome').val(data.nome)
                    $('#desc').val(data.desc)
                    $('#valor').val(data.valor)
                    $('#image').val(data.image)
                    $('#restaurants_id').val(data.restaurants_id)
                    $('#id').val(data.id)
                    $("#image").attr("src","/storage/"+data.image);


                }
            });


    });


</script>